# Generated by Django 5.1.1 on 2024-09-30 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categiry',
            new_name='Category',
        ),
    ]
