# Generated by Django 5.1.1 on 2024-10-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0002_rename_categiry_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='women',
            name='second_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
