# Generated by Django 5.1.1 on 2024-10-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0004_remove_women_time_create_remove_women_time_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='women',
            name='car',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
